//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompatibilityManager.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompatibilityManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick one or more executables to add to the list과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddFilesDescription {
            get {
                return ResourceManager.GetString("AddFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick a folder to add to the list.
        ///The application will recursively set flags on all executables found in this folder.
        ///If you pick something stupid like &quot;C:&quot;... well, you have been warned! :)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddFolderDescription {
            get {
                return ResourceManager.GetString("AddFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additional flags과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AdditionalFlags {
            get {
                return ResourceManager.GetString("AdditionalFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi-selection settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AggregatedSettings {
            get {
                return ResourceManager.GetString("AggregatedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compatibility Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This should never happen: if it happened, either all hell broke loose, a Windows update broke my stuff (fuck you too, Bill!), or (most likely) I&apos;m just a very bad programmer. Please report ASAP!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CatastrophicFailureException {
            get {
                return ResourceManager.GetString("CatastrophicFailureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear (remove from registry on save)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reduced color mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorMode {
            get {
                return ResourceManager.GetString("ColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16-bit (65536) color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorMode_COLOR16BIT {
            get {
                return ResourceManager.GetString("ColorMode_COLOR16BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8-bit (256) color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorMode_COLOR256 {
            get {
                return ResourceManager.GetString("ColorMode_COLOR256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run this program in compatibility mode for:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode {
            get {
                return ResourceManager.GetString("CompatibilityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows Vista과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_VISTARTM {
            get {
                return ResourceManager.GetString("CompatibilityMode_VISTARTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows Vista (Service Pack 1)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_VISTASP1 {
            get {
                return ResourceManager.GetString("CompatibilityMode_VISTASP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows Vista (Service Pack 2)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_VISTASP2 {
            get {
                return ResourceManager.GetString("CompatibilityMode_VISTASP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows 7과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_WIN7RTM {
            get {
                return ResourceManager.GetString("CompatibilityMode_WIN7RTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows 8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_WIN8RTM {
            get {
                return ResourceManager.GetString("CompatibilityMode_WIN8RTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows 95과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_WIN95 {
            get {
                return ResourceManager.GetString("CompatibilityMode_WIN95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows 98과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_WIN98 {
            get {
                return ResourceManager.GetString("CompatibilityMode_WIN98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows XP (Service Pack 2)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_WINXPSP2 {
            get {
                return ResourceManager.GetString("CompatibilityMode_WINXPSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows XP (Service Pack 3)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CompatibilityMode_WINXPSP3 {
            get {
                return ResourceManager.GetString("CompatibilityMode_WINXPSP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable fullscreen optimizations과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DisableFullscreenOptimizations {
            get {
                return ResourceManager.GetString("DisableFullscreenOptimizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Override high DPI scaling behavior.
        ///Scaling performed by:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DPIScaling {
            get {
                return ResourceManager.GetString("DPIScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DPIScaling_DPIUNAWARE {
            get {
                return ResourceManager.GetString("DPIScaling_DPIUNAWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System (Enhanced)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DPIScaling_GDIDPISCALING {
            get {
                return ResourceManager.GetString("DPIScaling_GDIDPISCALING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DPIScaling_HIGHDPIAWARE {
            get {
                return ResourceManager.GetString("DPIScaling_HIGHDPIAWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show HKLM (&quot;Change settings for all users&quot;)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Elevate {
            get {
                return ResourceManager.GetString("Elevate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be an Enum type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnumTypeArgumentException {
            get {
                return ResourceManager.GetString("EnumTypeArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExportDescription {
            get {
                return ResourceManager.GetString("ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Global Configuration]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GlobalConfig {
            get {
                return ResourceManager.GetString("GlobalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HKCU {
            get {
                return ResourceManager.GetString("HKCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local Machine과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HKLM {
            get {
                return ResourceManager.GetString("HKLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick a .reg file to import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ImportDescription {
            get {
                return ResourceManager.GetString("ImportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait...
        ///We&apos;re in the middle of some calibrations.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regedit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Regedit {
            get {
                return ResourceManager.GetString("Regedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload selected from registry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run in 640 x 480 resolution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Resolution640x480 {
            get {
                return ResourceManager.GetString("Resolution640x480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run this program as an administrator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RunAsAdministrator {
            get {
                return ResourceManager.GetString("RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save selected to registry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will save settings for each application to the registry.
        ///If no settings have been selected for an application, it will be removed from the registry entries.
        ///
        ///Confirm?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SaveWarning {
            get {
                return ResourceManager.GetString("SaveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t detect OS version. {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnknownOSException {
            get {
                return ResourceManager.GetString("UnknownOSException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unselect all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Here be dragons!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
