//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompatibilityManager.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WIN95")]
        public global::CompatibilityManager.Enums.CompatibilityMode LastCompatibilityMode
        {
            get
            {
                return ((global::CompatibilityManager.Enums.CompatibilityMode)(this["LastCompatibilityMode"]));
            }
            set
            {
                this["LastCompatibilityMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COLOR256")]
        public global::CompatibilityManager.Enums.ColorMode LastColorMode
        {
            get
            {
                return ((global::CompatibilityManager.Enums.ColorMode)(this["LastColorMode"]));
            }
            set
            {
                this["LastColorMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HIGHDPIAWARE")]
        public global::CompatibilityManager.Enums.DPIScaling LastDPIScaling
        {
            get
            {
                return ((global::CompatibilityManager.Enums.DPIScaling)(this["LastDPIScaling"]));
            }
            set
            {
                this["LastDPIScaling"] = value;
            }
        }
    }
}
